config/routes.rb
Rails4me::Application.routes.draw do

  get "search/index"

  get "admin/list"

  # Projects routing

  match '/projects/index' => 'projects#index', :as => 'projects_index'
  match '/projects/new' => 'projects#new', :as => 'new_project'
  match '/projects/show' => 'projects#show', :as => 'show_project'
  match '/projects/create' => 'projects#create', :as => 'create_project'
  match '/projects/edit' => 'projects#edit', :as => 'edit_project'
  match '/projects/update/:id' => 'projects#update', :as => 'update_project'
  match '/projects/destroy' => 'projects#destroy', :as => 'destroy_project'
  # Show project describes
  match '/projects/show_project_describes' => 'projects#show_project_describes', :as => 'show_project_describes'

  # Describes routing

  match '/describes/index' => 'describes#index', :as => 'describes_index'
  match '/describes/new' => 'describes#new', :as => 'new_describe'
  match '/describes/create' => 'describes#create', :as => 'create_describe'
  match '/describes/edit' => 'describes#edit', :as => 'edit_describe'
  match '/describes/update/:id' => 'describes#update', :as => 'update_describe'
  match '/describes/destroy' => 'describes#destroy', :as => 'destroy_describe'
  match '/describes/show_describe_information' => 'describes#show_describe_information', :as => 'show_describe_information'

  # Admin routing

  match '/admin/list' => 'admin#list', :as => 'admin_list'
  match '/admin/show' => 'admin#show', :as => 'admin_show'

  # Search Routing

  match '/search/search' => 'search#search', :as => 'search'
  match '/search/founded_items' => 'search#founded_items', :as => 'founded_items'


  #-------------------------------------------------------------------------------------------------------------------#
  #-------------------------------------------------------------------------------------------------------------------#

  # Others

  root :to => "frontend#index"
  get "backend/index"
  # resources :describes
  # match '/describes/:id' => 'describes#show', :as => 'backend_describe_show', :path => '/backend/describe/:id'
  # match '/backend/search' => 'backend#search', :as => 'search', :path => '/backend/search'

  devise_for :admins do
    get "admin", :to => "devise/sessions#new"
  end

  #scope :path_names => { :show_all => "allprojects" } do
  #  resources :describes do
  #    get 'show_all', :on => :member
  #  end
  # end

  resources :frontend do
    member do
      get 'show'
    end
  end

end

app/models/describe.rb
class Describe < ActiveRecord::Base
  belongs_to :project

  #search

  def self.search(search)
    if search
      # find(:all, :conditions => ['title LIKE ? OR project_id LIKE ? ', "%#{search}%", "%#{search}%" ] )
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"] )
    else
      find(:all)
    end
  end

  def self.something_value(value)
  end

end

app/controllers/describes_controller.rb
class DescribesController < ApplicationController

  before_filter :authenticate_admin!
  layout "backend"

  def index
    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      @describes = Describe.find(:all)
      # render :json => { :success => :true, :describes => @describes}
      respond_to do |format|
        format.xml
      end

    end
  end

  def show
    # @show_valtozo = "Ez itt az!!!!"
    @projects = Project.find(:all)
    @describes = Describe.find(:all)
    @describe = Describe.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @describe }
    end
  end

  def show_all
   if(params[:id])
     @describes = Describe.where("project_id = ?", params[:id])
     redirect_to describes_path, :notice => "Already you have not describe to this project!" if @describes.empty?
   end
  end

  def new
    @projects = Project.find(:all)
    @describe = Describe.new
    respond_to do |format|
      format.js
    end
  end


  def edit

    @describe_id = params[:id]
    @describe = Describe.find(@describe_id)
    @project_id = @describe.project.id
    @project = Project.find(@project_id)

    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      # render :json => {:success => true, :founded_describe => @describe}
      render :json => {
          :success => true,
          data: {
              id: "#{@describe.id}",
              title: "#{@describe.title}",
              short_description: "#{@describe.short_description}",
              long_description: "#{@describe.long_description}",
              keywords: "#{@describe.keywords}",
              gitlink: "#{@describe.gitlink}",
              feedback: "#{@describe.feedback}",
              project_id: "#{@describe.project_id}"
          }
      }
    end
  end

  def create
    @describe = Describe.new(params[:describe])    
      if @describe.save
        render :json => {:success => true}
      else
        render :json => {:failure => true}
      end    
  end

  def update
    @describe = Describe.find(params[:id])

    if @describe.update_attributes(
        :title => params[:title],
        :short_description => params[:short_description],
        :long_description => params[:long_description],
        :keywords => params[:keywords],
        :gitlink => params[:gitlink],
        :feedback => params[:feedback],
        :public => params[:public],
        :project_id => params[:project_id]
    )
      render :json => {:success => true}
    else
      render :json => {:failure => true}
    end
  end

  def destroy
    @describe = Describe.find(params[:id])
    if @describe.destroy
     render :json => {:success => true}
    else
     render :json => {:failure => true}
    end
  end

  def ajax_public
    @describe = Describe.find(params[:id])
    if params[:public] == "true"
      @describe.update_attributes(:public => false)
      redirect_to describes_path
    elsif params[:public] == "false"
      @describe.update_attributes(:public => true)
      redirect_to describes_path
    end
  end

  def show_describe_information
   @describe = Describe.find(params[:id])
  end

end

app/helpers/describes_helper.rb
module DescribesHelper
end

app/helpers/models/describe.rb
class Describe < ActiveRecord::Base
  belongs_to :project
end

app/views/describes/_form.html.erb
<%= form_for(@describe) do |f| %>
  <% if @describe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@describe.errors.count, "error") %> prohibited this describe from being saved:</h2>

      <ul>
      <% @describe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :public, "Public to frontend?" %><br />
    <%= f.select( :public, { "Yes" => "1", "No!" => "0"}, :selected => @selected_value ) %>
  </div>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field" id="short_description_beallitasa">
    <%= f.label :short_description %><br />
    <%= f.cktext_area :short_description, :toolbar=>'light', :width=>'690px', :height=>'100px', :skin => "v2" %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br />
    <%= f.cktext_area :long_description, :toolbar=>'basic', :width=>'690px', :height=>'400px', :skin => "v2" %>
  </div>
  <div class="span-18">
    <div class="span-6">
      <div class="field">
        <%= f.label :keywords %><br />
        <%= f.text_field :keywords %>
      </div>     
    </div>
    <div class="span-6">
      <div class="field">
        <%= f.label :feedback %><br />
        <%= f.text_field :feedback %>
      </div>      
    </div>    
    <div class="span-6 last">
      <div class="field">
        <%= f.label :gitlink %><br />
        <%= f.text_field :gitlink %>
      </div>    
    </div>
  </div>
  <div class="field">
    <%= f.label :project_id, "Which project?" %><br />
    <%= f.select("project_id", Project.all.collect {|project| [ project.name, project.id ] }) %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :class => "submit" %>    
  </div>
<% end %>

app/views/describes/edit.js.erb
Ext.QuickTips.init();

var edit_describe_form = new Ext.form.FormPanel({

    id: 'edit_describe_form',
    url: '<%= update_describe_path(@describe_id) %>',
    labelWidth: 130,
    renderTo: Ext.getBody(),
    frame: true,
    /*autoWidth: true,*/

    items:[
        {
            xtype: 'textfield',
            hidden: true,
            name: 'id'
        },
        {
            xtype: 'textfield',
            fieldLabel: 'Title',
            allowBlank: false,
            width: '98%',
            name: 'title'
        },
        {
            xtype: 'textarea',
            fieldLabel: 'Short description',
            name: 'short_description',
            width: '98%',
            height: 50
        },
        {
            xtype: 'ckeditor',
            fieldLabel: 'Long description',
            name: 'long_description',
            CKConfig: {
                /* Enter your CKEditor config paramaters here or define a custom CKEditor config file. */
                toolbar: 'light',
                uiColor: '#ddd',
                height : 150,
                width: 634
            }
        },
        {
            xtype: 'textfield',
            fieldLabel: 'Keywords',
            width: '98%',
            name: 'keywords',
            emptyText: 'No Keywords'
        },
        {
            xtype: 'textfield',
            fieldLabel: 'Gitlink',
            width: '98%',
            name: 'gitlink',
            emptyText: 'No Gitlink'
        },

        {
            xtype: 'textfield',
            fieldLabel: 'Feedback link',
            width: '98%',
            name: 'feedback',
            emptyText: 'No Feedback'
        },

        {
            xtype: 'combo',
            width: '98%',
            id: 'project_combo_store',
            fieldLabel: 'Project',
            hiddenName: 'project_id',
            mode: 'local',
            allowBlank: false,
            valueField: 'id',
            displayField: 'name',
            labelStyle: 'font-weight:bold; color: orange;',

            store: new Ext.data.Store({
                reader: new Ext.data.JsonReader({
                    fields: [
                        {name: "id",   mapping: "id"},
                        {name: "name", mapping: "name"}
                    ]
                }),
                proxy: new Ext.data.HttpProxy({
                    url: '<%= projects_index_path(:need_data => 'true') %>'
                }),
                autoLoad: true,
            })

        },

        {
            xtype: 'combo',
            id: 'public_combo',
            allowBlank: false,
            fieldLabel: 'Public',
            hiddenName: 'public',
            width: '98%',
            emptyText:'Select something...',
            mode: 'local',
            store: new Ext.data.ArrayStore({
                id: 0,
                fields: [
                  'value',
                  'displayText'
                ],
                data: [[true, 'Public'], [false, 'Non public']]
            }),
            valueField: 'value',
            displayField: 'displayText',

            listeners: {
                select: function() {
                      Ext.Msg.alert('Do you really wanna?!');
                }
            }
        }

    ],

    buttons:[
        {

            text: 'Update',
            icon: '../images/exticons/save.png',
            handler: function() {
                edit_describe_form.getForm().submit({
                    success: function(form, action) {
                        // If we come from describes side wont live the project_describes_list_grid we must check it
                        if (Ext.getCmp('edit_project_window')) {
                         Ext.getCmp('edit_project_window').close();
                         Ext.getCmp('project_list_grid').store.reload();
                        }

                        Ext.getCmp('edit_describe_form_window').close();
                        Ext.Msg.alert('Success!', 'You saved the new describe to database successfully!');

                        // If we come from projects side, and update
                        // wont live the describes_list_grid we must check it
                        if (Ext.getCmp('describes_list_grid')) {
                          Ext.getCmp('describes_list_grid').store.reload();
                        }

                    },
                    failure: function(form, action) {
                        Ext.Msg.show({
                            title: 'Rails4me_app',
                            msg: 'Cannot saved into the database,<br/> please check your fields!',
                            icon: Ext.MessageBox.INFO,
                            buttons: Ext.MessageBox.OK
                        });
                    }
                });

            }

        },

        {

            text: 'Cancel',
            icon: '../images/exticons/cancel.png',
            handler: function() {
                Ext.getCmp('edit_describe_form_window').close();
            }

        }

    ]

});

var new_describe_window = new Ext.Window({
    id: 'edit_describe_form_window',
    scrollable: true,
    autoHeight: false,
    width: 800,
    modal: true,
    layout: 'form',
    title: 'Edit the describe',

    items: [
      // Load form into window
      edit_describe_form
    ]
});

new_describe_window.show();

// Load data from server database
edit_describe_form.getForm().load({
    method:'get',
    url: '<%= edit_describe_path(:id => @describe_id, :need_data => 'true')%>',
    waitMsg: 'Loading data...'
});

// set the combo value to database value
Ext.getCmp('public_combo').setValue(<%= @describe.public %>);

app/views/describes/index.html.erb
<h1>Describe list</h1>

<div class="span-18">
  <div id="uj_leiras_gomb">
    <%= link_to image_tag("create_describe.jpg"), new_describe_path%>
  </div>
</div>

<div class="clear"></div>

<div id="describe_lista_fejlec">

  <div class="span-18">
    <div class="span-11">
      <div class="describe_text">
        <strong>Describe name</strong>
      </div>
    </div>

    <div class="span-2">
      <div class="describe_text_action">
        <strong>Public?</strong>
      </div>
    </div>
    
    <div class="span-4 append-1 last" id="describe_action">
      <div class="describe_text_action">
        <strong>Describe action</strong>
      </div>
    </div>
  </div>

</div>

<br/><br/>

<% @describes.each do |describe| %>

  <div class="describe_lista_elem">

    <div class="span-11">
      <div class="describe_text">
        <% title = truncate("#{describe.title}", :length => 80, :omission => "...") %>
        <b><%= link_to "#{title}", backend_describe_show_path(describe) %></b>
      </div>
    </div>

    <div class="span-2">
      <div class="describe_public_action">
          <% if describe.public? %>
            <div class="ajax">
              <!-- ajax response -->
            </div>
            <div class="original">
              <%= link_to "Yes", ajax_public_path(describe, :public => "true" )%>
            </div>
          <% else %>
            <div class="ajax">
              <!-- ajax response -->
            </div>
            <div class="no_public">
              <%= link_to "No", ajax_public_path(describe, :public => "false" )%>
            </div>
          <% end %>
      </div>
    </div>

    <div class="span-4 append-1 last">
      <div class="describe_text_action">
        <%= link_to 'Edit', edit_describe_path(describe) %> &nbsp; OR &nbsp;
        <%= link_to 'Destroy', describe, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>

  </div>

<% end %>

<div class="span-18">
  <br/><br/>
  <%= link_to 'Back to start site', backend_index_path, :class => "button" %>
  <br/><br/>
</div>

app/views/describes/index.js.erb
// Record definition

var describes_data = Ext.data.Record.create([
    'id',
    'title',
    'short_description',
    'public'
]);

// Store

var describes_store = new Ext.data.Store({
    url: '<%= describes_index_path(:need_data => 'true') %>',
    reader: new Ext.data.XmlReader({
        record:'row'                  // The repeated element which contains row information
        // idPath:'id',
        // totalProperty: "results",   // The element which contains the total dataset size (optional)
        // idProperty: "id",           // The element within the row that provides an ID for the record (optional)
        // messageProperty: "msg"
    }, describes_data),
    autoLoad: true
});

var describes_grid = new Ext.grid.GridPanel({
    id: 'describes_list_grid',
    closable: true,
    title : 'Describes list',
    renderTo : Ext.getBody(),
    store: describes_store,
    autoHeight : true,
    loadMask: true,

    // VIEW

    view : new Ext.grid.GridView(),

    // SELMODEL

    selModel : new Ext.grid.RowSelectionModel({
        singleSelect : true
    }),

    // COLMODEL

    colModel: new Ext.grid.ColumnModel([
        {
            hidden: true,
            dataIndex : 'id'
        },
        {
            header : 'Describe name',
            sortable : true,
            width: '300px',
            dataIndex : 'title'
        },
        {
            header : 'Describe short description',
            sortable : true,
            width: '500px',
            dataIndex : 'short_description'
        },
        {
            header : 'Public',
            sortable : true,
            width: '250px',
            dataIndex : 'public'
        }
    ]),

    // LISTENER

    listeners : {
        rowdblclick: function(dv, record, item, index, e) {
            var record = describes_grid.selModel.getSelected();
            Ext.Ajax.request({
                url: '<%= edit_describe_path %>',
                params: {
                  id: record.data.id
                },
                success: function(response) {
                    var response_text = response.responseText;
                    eval(response_text);
                },
                failure: function(resp) {
                    Ext.Msg.alert('Error!', 'Bad response from server!');
                }
            });
        }
    }

});

  var describes_index_window = new Ext.Window({
    id: 'desc_window',
    autoHeight: true,
    maximizable : true,
    modal: true,
    // y: 200,
    width: 1140,
    layout: 'fit',
    title: 'Rails4me describes',

    items: [
      describes_grid
    ],

    tbar: [
        {
           xtype : 'button',
           icon: '../images/exticons/add_project.png',
           text  : 'Create a new describe',
            handler: function() {
                Ext.Ajax.request({
                    url: '<%= new_describe_path %>',
                    success: function(response) {
                        var response_text = response.responseText;
                        eval(response_text);
                    },
                    failure: function(resp) {
                        if (resp.status == "401") {
                          // Ext.Msg.alert('Error!', "Your session expired, please sign in again to continue." + resp.status);
                          Ext.Msg.alert('Name', 'Your session expired, please sign in again to continue.', function(btn) {
                              if (btn == 'ok') {
                                 location.href='http://rails44me.heroku.com/admins/sign_in';
                              }
                          });
                        }
                        else {
                          Ext.Msg.alert('Error!', "Bad response from server!");
                        }

                    }
                });
            }
        },
        '-',
        {
           xtype : 'button',
           id: 'edit',
           icon: '../images/exticons/edit_project.png',
           text  : 'Edit selected describe',
           listeners : {
                click: function() {
                    var selected_row = describes_grid.selModel.getSelected();
                    if (describes_grid.getSelectionModel().hasSelection()) {
                        Ext.Ajax.request({
                            url: '<%= edit_describe_path %>',
                            method: 'POST',
                            params: {
                                id: selected_row.data.id
                            },
                            success: function(response) {
                                var response_text = response.responseText;
                                eval(response_text);
                            },
                            failure: function(resp) {
                                Ext.Msg.alert('ERROR!', resp);
                            }
                        });
                    }
                    else {
                        Ext.Msg.alert('ERROR!', 'Please first select a row!');
                    }
                }
           }

        },
        '-',
        {
            xtype : 'button',
            icon: '../images/exticons/delete_project.png',
            text  : 'Remove selected describe',
            handler: function() {
                var selected_row = describes_grid.getSelectionModel().getSelected();
                if (describes_grid.getSelectionModel().hasSelection()) {

                    Ext.Msg.show({
                        title:'Save Changes?',
                        msg: 'Would you like to delete selected describe?',
                        buttons: Ext.Msg.YESNOCANCEL,
                        icon: Ext.MessageBox.QUESTION,
                        fn: function(btn){
                          if (btn == 'yes') {

                              Ext.Ajax.request({
                                  waitMsg: "Please wait",
                                  url: '<%= destroy_describe_path %>',
                                  method: 'POST',
                                  params: {
                                      id: selected_row.data.id
                                  },
                                  success: function() {
                                      Ext.Msg.alert('Success!', 'Sucessfully destroyed the describe!');
                                      Ext.getCmp('describes_list_grid').getStore().reload();
                                      // var response_text = response.responseText;
                                      // eval(response_text);
                                  },
                                  failure: function() {
                                      Ext.Msg.alert('Error!', 'Bad response from server!');
                                  }
                              });

                          }
                        }
                    });
                }
                else {
                    Ext.Msg.alert('ERROR!', 'Please first select a row!');
                }
            }
        }
    ],

    bbar: [
        {
            xtype : 'button',
            icon: '../images/exticons/worksheet.png',
            text  : ' Information / Worksheet selected describe',
            listeners: {
                click: function(){
                   var selected_row = describes_grid.getSelectionModel().getSelected();
                   if (describes_grid.getSelectionModel().hasSelection()) {
                       Ext.Ajax.request({
                           url: '<%= show_describe_information_path %>',
                           method: 'POST',
                           params: {
                               id: selected_row.data.id
                           },
                           success: function(response) {
                               var response_text = response.responseText;
                               eval(response_text);
                           },
                           failure: function(resp) {
                               Ext.Msg.alert('ERROR!', 'Bad response from server!');
                           }
                       });
                   }
                   else {
                     Ext.Msg.alert('ERROR!', 'Please first select a row!');
                   }
                }
            }

        }
    ]

});
describes_index_window.show();

app/views/describes/new.js.erb
<% if @projects == [] %>
  /* If no projects show warning message!*/
  Ext.Msg.alert('WARNING!', "No Describes, please check first the projects!");
<% else %>

  Ext.QuickTips.init();

var new_describe_form = new Ext.form.FormPanel({
    url: '<%= create_describe_path %>',
    labelWidth: 130,
    renderTo: Ext.getBody(),
    frame: true,
    /*autoWidth: true,*/
    items:[
        {
            xtype: 'textfield',
            fieldLabel: 'Title',
            allowBlank: false,
            width: '98%',
            name: 'describe[title]'
        },

        {
            xtype: 'textarea',
            fieldLabel: 'Short description',
            name: 'describe[short_description]',
            width: '98%'
        },
        {
            xtype: 'ckeditor',
            fieldLabel: 'Long description',
            name: 'describe[long_description]',
            CKConfig: {
                /* Enter your CKEditor config paramaters here or define a custom CKEditor config file. */
                toolbar: 'light',
                uiColor: '#dfe8f6',
                height : 100,
                width: 533
            }
        },

        {
            xtype: 'textfield',
            fieldLabel: 'Keywords',
            width: '98%',
            name: 'describe[keywords]'
        },

        {
            xtype: 'textfield',
            fieldLabel: 'Gitlink',
            width: '98%',
            name: 'describe[gitlink]'
        },

        {
            xtype: 'textfield',
            fieldLabel: 'Feedback link',
            width: '98%',
            name: 'describe[feedback]'
        },

        {
            xtype: 'combo',
            fieldLabel: 'Project ID',
            width: '98%',
            hiddenName: 'describe[project_id]',
            id: 'project_combo_store',
            mode: 'local',
            allowBlank: false,
            valueField: 'id',
            displayField: 'name',
            store: new Ext.data.Store({
                reader: new Ext.data.JsonReader({
                    fields: [
                        {name: "id",   mapping: "id"},
                        {name: "name", mapping: "name"}
                    ]
                }),
                proxy: new Ext.data.HttpProxy({
                    url: '<%= projects_index_path(:need_data => 'true') %>'
                }),
                autoLoad: true
            })

        },

        {
            xtype: 'combo',
            id: 'public_combo',
            fieldLabel: 'Public',
            hiddenName: 'describe[public]',
            allowBlank: false,
            width: '98%',
            emptyText:'Select something...',
            mode: 'local',
            store: new Ext.data.ArrayStore({
                id: 0,
                fields: [
                  'value',
                  'displayText'
                ],
                data: [[true, 'Public'], [false, 'Non public']]
            }),
            valueField: 'value',
            displayField: 'displayText'

        }

    ],

    buttons:[
        {

            text: 'Save',
            icon: '../images/exticons/save.png',
            handler: function() {
                new_describe_form.getForm().submit({
                    success: function(form, action) {
                        Ext.getCmp('describes_list_grid').getStore().reload();
                        Ext.getCmp('new_describe_form_window').close();
                        Ext.Msg.alert('Success!', 'You saved the new describe to database successfully!');
                    },
                    failure: function(form, action) {
                        Ext.Msg.alert('Error!', 'Bad response from server');
                    }
                });

            }

        },

        {

            text: 'Cancel',
            icon: '../images/exticons/cancel.png',
            handler: function() {
                Ext.getCmp('new_describe_form_window').close();
            }

        }

    ]

});

var new_describe_window = new Ext.Window({
    id: 'new_describe_form_window',
    autoHeight: true,
    width: 700,
    modal: true,
    layout: 'form',
    title: 'Create a new describe',

    items: [
      // Load form into window
      new_describe_form
    ]
});

new_describe_window.show();

<% end %>

app/views/describes/show.html.erb
<p id="notice"><%= notice %></p>

<!-- FORMAT TIME -->
  <%
    t = @describe.created_at
    month = t.strftime("%b")
    day = t.strftime("%e")
  %>

<div class="span-17" id="describe_background">

    <div class="span-17">
      <div class="span-1">
        <%= image_tag("date_icon.jpg", :class => "main_date") %>
        <div class="date_box">
          <div class="month"><%= month %></div>
          <div class="day"><%= day %></div>
        </div>
      </div>
      <div class="span-15" id="main_title"><%= @describe.title %></div>
      <div class="span-1 last"></div>
    </div>

    <div class="span-17">
      <div class="main_short_description"><div class="describe_list_text"><%= raw @describe.short_description %></div></div>
      <div class="main_long_description"><div class="describe_list_text"><%= raw @describe.long_description %></div></div>      
    </div>

  </div>

<div class="span-17 append-1">
  <div class="span-6">

    <div class="link_feedback">
      <% if @describe.feedback.blank? %>
      <b>No link</b> to this describe!
      <% else %>
        <%= link_to "Direct link to the description!", @describe.feedback %>
      <% end %>
    </div>

  </div>

  <div class="span-6" id="gitlink">
   
    <div class="link_github">
      <% if @describe.gitlink.blank? %>
      <b>No gitlink</b> to this describe!
      <% else %>
        <%= link_to "Direct gitlink to the description!", @describe.gitlink %>
      <% end %>      
    </div>

  </div>

  <div class="span-5 last">
    <div class="edit">
      <%= link_to "Edit describe!", edit_describe_path(@describe.id) %>
    </div>
  </div>

</div>

<div class="span-17 append-1">
  <div class="informacio_email">
    If you have any questions please mail me! (oladipeter@gmail.com)
  </div>
</div>

app/views/describes/show_describe_information.js.erb
var show_describe_information = new Ext.Window({
    id: 'show_describe_information',
    width: 600,
    height: 300,
    padding: 10,
    modal: true,
    autoScroll: true,
    layout: 'form',
    title: '<%= @describe.title %>',
    html: '<div class="describe_title"><%= raw @describe.short_description %></div><br/><div class="describe_container"><%= raw @describe.long_description %></div>',

    tbar:[
        {
            xtype: 'button',
            text: 'Edit the \"<%= @describe.title %>\" describe',
            listeners: {
              click: function() {
                  Ext.Ajax.request({
                      url: '<%= edit_describe_path %>',
                      method: 'POST',
                      params: {
                          id: '<%= @describe.id %>'
                      },
                      success: function(response) {
                          var response_text = response.responseText;
                          eval(response_text);
                      },
                      failure: function(resp) {
                          Ext.Msg.alert('ERROR!', 'Bad response from server!');
                      }
                  });
              }
            }
        }
    ]

});

show_describe_information.show();