config/routes.rb
Rails4me::Application.routes.draw do

  get "search/index"

  get "admin/list"

  # Projects routing

  match '/projects/index' => 'projects#index', :as => 'projects_index'
  match '/projects/new' => 'projects#new', :as => 'new_project'
  match '/projects/show' => 'projects#show', :as => 'show_project'
  match '/projects/create' => 'projects#create', :as => 'create_project'
  match '/projects/edit' => 'projects#edit', :as => 'edit_project'
  match '/projects/update/:id' => 'projects#update', :as => 'update_project'
  match '/projects/destroy' => 'projects#destroy', :as => 'destroy_project'
  # Show project describes
  match '/projects/show_project_describes' => 'projects#show_project_describes', :as => 'show_project_describes'

  # Describes routing

  match '/describes/index' => 'describes#index', :as => 'describes_index'
  match '/describes/new' => 'describes#new', :as => 'new_describe'
  match '/describes/create' => 'describes#create', :as => 'create_describe'
  match '/describes/edit' => 'describes#edit', :as => 'edit_describe'
  match '/describes/update/:id' => 'describes#update', :as => 'update_describe'
  match '/describes/destroy' => 'describes#destroy', :as => 'destroy_describe'
  match '/describes/show_describe_information' => 'describes#show_describe_information', :as => 'show_describe_information'

  # Admin routing

  match '/admin/list' => 'admin#list', :as => 'admin_list'
  match '/admin/show' => 'admin#show', :as => 'admin_show'

  # Search Routing

  match '/search/search' => 'search#search', :as => 'search'
  match '/search/founded_items' => 'search#founded_items', :as => 'founded_items'


  #-------------------------------------------------------------------------------------------------------------------#
  #-------------------------------------------------------------------------------------------------------------------#

  # Others

  root :to => "frontend#index"
  get "backend/index"
  # resources :describes
  # match '/describes/:id' => 'describes#show', :as => 'backend_describe_show', :path => '/backend/describe/:id'
  # match '/backend/search' => 'backend#search', :as => 'search', :path => '/backend/search'

  devise_for :admins do
    get "admin", :to => "devise/sessions#new"
  end

  #scope :path_names => { :show_all => "allprojects" } do
  #  resources :describes do
  #    get 'show_all', :on => :member
  #  end
  # end

  resources :frontend do
    member do
      get 'show'
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :describe
end

app/models/describe.rb
class Describe < ActiveRecord::Base
  belongs_to :project

  #search

  def self.search(search)
    if search
      # find(:all, :conditions => ['title LIKE ? OR project_id LIKE ? ', "%#{search}%", "%#{search}%" ] )
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"] )
    else
      find(:all)
    end
  end

  def self.something_value(value)
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :describes
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def list

    @admins = Admin.find(:all)
    @all_of_admins = @admins.size

    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.xml
      end
    end

  end

  def show
    @admin = Admin.find(params[:id])
    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.xml
      end
    end
  end

end

app/controllers/backend_controller.rb
class BackendController < ApplicationController

  before_filter :authenticate_admin!
  layout "backend"

  def index
    @projects = Project.find(:all)
    @describes = Describe.find(:all)
  end

  def search
    @describes = Describe.search(params[:title])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.xml
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment, :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController

  layout "frontend"  

  def index
    @projects = Project.find(:all)
    @describes = Describe.find(:all, :conditions => { :public => true }, :order => "created_at DESC")
    @public_describes = @describes.size
    @all_of_describes = Describe.find(:all).size
  end

  def show
      @projects = Project.find(:all)
      @describes = Describe.where( :public => true )
      @describe = Describe.find(params[:id])      
        
      # if describe not public redirect to index
      unless @describe.public
        redirect_to :action => :index
      end
  end

end

app/controllers/jquery_controller.rb
class JqueryController < ApplicationController
  def index
    @describe = Describe.new
    @describes = Describe.find(:all)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.xml
      end
    end
  end

  def founded_items

    unless params[:need_data]  # Just appear the window
      respond_to do |format|
        @search_value = params[:search_value] # in the window send request with this param
        @describes = Describe.search(params[:search_value]) # Search in database
        if @describes == [] # If result is empty array
         format.js { render :partial => "no_result.js.erb" }
        else
         format.js # founded items js will run, and that code do another request wth need_data
        end
      end
    else
      respond_to do |format|
        @describes = Describe.search(params[:search_value])
        format.xml
      end
    end

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :authenticate_admin!
  
  def start
    @projects = Project.find(:all)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def capitalized_the_text(text)
    cap_text = text.capitalize!
  end

  def truncate_the_text(text, length)
    truncated_text = truncate(text, :length => length)
  end

end

app/helpers/backend_helper.rb
module BackendHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/describes_helper.rb
module DescribesHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/jquery_helper.rb
module JqueryHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Content</th>
    <th>Email</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.author %></td>
    <td><%= comment.content %></td>
    <td><%= comment.email %></td>
    <td><%= comment.website %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>Email:</b>
  <%= @comment.email %>
</p>

<p>
  <b>Website:</b>
  <%= @comment.website %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/search/_no_result.js.erb
Ext.Msg.alert('Search', 'No item in database try again!');

app/views/search/founded_items.js.erb
// Record definition

var search_result = Ext.data.Record.create([
    'title',
    'short_description',
    'created_at'
    // 'director',
    // 'runtime',
    // {name: 'released', type: 'date', dateFormat: 'Y-m-d'},
    // 'genre',
    // 'tagline',
    // {name: 'price', type: 'float'},
    // {name: 'available', type: 'bool'}

    /* name:
       The name by which the field will be referenced.

       type:
       The data type in which the raw data item will be converted to when
       stored in the record. Values may be 'int', 'float', 'string', 'date',
       or 'bool'.

       dateFormat:
       If the type of data to be held in the field is a date type, then
       we need to specify a format string as used by the Date.parseDate function.
    */
]);

// Store

var store = new Ext.data.Store({
    url: '<%= founded_items_path(:need_data => true, :search_value => @search_value)%>',
    reader: new Ext.data.XmlReader({
        record:'row'                  // The repeated element which contains row information
        // idPath:'id',
        // totalProperty: "results",   // The element which contains the total dataset size (optional)
        // idProperty: "id",           // The element within the row that provides an ID for the record (optional)
        // messageProperty: "msg"
    }, search_result),
    autoLoad: true
});

// Grid

var search_result_grid = new Ext.grid.GridPanel({
    renderTo: Ext.getBody(),
    frame: true,
    title: 'Admin Database',
    autoHeight: true,
    width: 700,
    store: store,
    colModel: new Ext.grid.ColumnModel({
        defaultSortable: true,
        columns: [
            {header: "Title",             dataIndex: 'title',             width: 500},
            {header: "Short Description", dataIndex: 'short_description', width: 200},
            {header: "Created",           dataIndex: 'created_at',        width: 100}
        ]
    })
});

var search_result_window = new Ext.Window({
    id: 'search_result_window',
    autoHeight: true,
    y: 200,
    width: 600,
    modal: true,
    layout: 'form',
    title: 'Find in contents!',
    html: 'Ez van a title-ben : <%= @title %>',

    items: [
      search_result_grid
    ]

});

search_result_window.show();

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/search/search.html.erb
<h1>Search#search</h1>
<p>Find me in app/views/search/search.html.erb</p>

app/views/search/search.js.erb
Ext.QuickTips.init();

var search_form = new Ext.form.FormPanel({
    url: '<%= founded_items_path  %>',
    labelWidth: 130,
    renderTo: Ext.getBody(),
    frame: true,
    autoWidth: true,
    items:[
        {
            xtype: 'label',
            html: "<b>Find in all describes and more...<b><br/><br/>"
        },

        {
            xtype: 'textfield',
            id: 'title_field',
            fieldLabel: 'Title',
            width: '98%',
            name: 'title'
        }

    ],

    buttons:[
        {

            text: 'Search!',
            icon: '../images/exticons/save.png',
            handler: function() {

                // User write value into the textfield
                var search_value = Ext.getCmp('title_field').getValue();

                Ext.Ajax.request({
                    url: '<%= founded_items_path %>',
                    params: {
                        search_value : search_value // Send this parameter to founded items method
                    },
                    success: function(response) {
                        var response_text = response.responseText;
                        eval(response_text);
                    },
                    failure: function(resp) {
                        Ext.Msg.alert('Error!', 'Bad response from server!');
                    }
                });

                /*search_form.getForm().submit({
                    success: function(response) {
                       var response_text = response.responseText;
                       eval(response_text);
                    },
                    failure: function(form, action) {
                        Ext.Msg.show({
                            title: 'Rails4me_app',
                            msg: 'Cannot found into the database!',
                            icon: Ext.MessageBox.INFO,
                            buttons: Ext.MessageBox.OK
                        });
                    }
                });*/



            }

        }
    ]

});

var new_project_window = new Ext.Window({
    id: 'new_search_form_window',
    autoHeight: true,
    y: 200,
    width: 600,
    modal: true,
    layout: 'form',
    title: 'Find in contents!',

    items: [
      // Load form into window
      search_form
    ]
});

new_project_window.show();