config/routes.rb
Rails4me::Application.routes.draw do

  get "search/index"

  get "admin/list"

  # Projects routing

  match '/projects/index' => 'projects#index', :as => 'projects_index'
  match '/projects/new' => 'projects#new', :as => 'new_project'
  match '/projects/show' => 'projects#show', :as => 'show_project'
  match '/projects/create' => 'projects#create', :as => 'create_project'
  match '/projects/edit' => 'projects#edit', :as => 'edit_project'
  match '/projects/update/:id' => 'projects#update', :as => 'update_project'
  match '/projects/destroy' => 'projects#destroy', :as => 'destroy_project'
  # Show project describes
  match '/projects/show_project_describes' => 'projects#show_project_describes', :as => 'show_project_describes'

  # Describes routing

  match '/describes/index' => 'describes#index', :as => 'describes_index'
  match '/describes/new' => 'describes#new', :as => 'new_describe'
  match '/describes/create' => 'describes#create', :as => 'create_describe'
  match '/describes/edit' => 'describes#edit', :as => 'edit_describe'
  match '/describes/update/:id' => 'describes#update', :as => 'update_describe'
  match '/describes/destroy' => 'describes#destroy', :as => 'destroy_describe'
  match '/describes/show_describe_information' => 'describes#show_describe_information', :as => 'show_describe_information'

  # Admin routing

  match '/admin/list' => 'admin#list', :as => 'admin_list'
  match '/admin/show' => 'admin#show', :as => 'admin_show'

  # Search Routing

  match '/search/search' => 'search#search', :as => 'search'
  match '/search/founded_items' => 'search#founded_items', :as => 'founded_items'


  #-------------------------------------------------------------------------------------------------------------------#
  #-------------------------------------------------------------------------------------------------------------------#

  # Others

  root :to => "frontend#index"
  get "backend/index"
  # resources :describes
  # match '/describes/:id' => 'describes#show', :as => 'backend_describe_show', :path => '/backend/describe/:id'
  # match '/backend/search' => 'backend#search', :as => 'search', :path => '/backend/search'

  devise_for :admins do
    get "admin", :to => "devise/sessions#new"
  end

  #scope :path_names => { :show_all => "allprojects" } do
  #  resources :describes do
  #    get 'show_all', :on => :member
  #  end
  # end

  resources :frontend do
    member do
      get 'show'
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :describe
end

app/models/describe.rb
class Describe < ActiveRecord::Base
  belongs_to :project

  #search

  def self.search(search)
    if search
      # find(:all, :conditions => ['title LIKE ? OR project_id LIKE ? ', "%#{search}%", "%#{search}%" ] )
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"] )
    else
      find(:all)
    end
  end

  def self.something_value(value)
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :describes
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def list

    @admins = Admin.find(:all)
    @all_of_admins = @admins.size

    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.xml
      end
    end

  end

  def show
    @admin = Admin.find(params[:id])
    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.xml
      end
    end
  end

end

app/controllers/backend_controller.rb
class BackendController < ApplicationController

  before_filter :authenticate_admin!
  layout "backend"

  def index
    @projects = Project.find(:all)
    @describes = Describe.find(:all)
  end

  def search
    @describes = Describe.search(params[:title])
  end

end

app/controllers/jquery_controller.rb
class JqueryController < ApplicationController
  def index
    @describe = Describe.new
    @describes = Describe.find(:all)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.xml
      end
    end
  end

  def founded_items

    unless params[:need_data]  # Just appear the window
      respond_to do |format|
        @search_value = params[:search_value] # in the window send request with this param
        @describes = Describe.search(params[:search_value]) # Search in database
        if @describes == [] # If result is empty array
         format.js { render :partial => "no_result.js.erb" }
        else
         format.js # founded items js will run, and that code do another request wth need_data
        end
      end
    else
      respond_to do |format|
        @describes = Describe.search(params[:search_value])
        format.xml
      end
    end

  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def capitalized_the_text(text)
    cap_text = text.capitalize!
  end

  def truncate_the_text(text, length)
    truncated_text = truncate(text, :length => length)
  end

end

app/helpers/backend_helper.rb
module BackendHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/describes_helper.rb
module DescribesHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/jquery_helper.rb
module JqueryHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/list.js.erb
// Record definition

var Admin = Ext.data.Record.create([
    'id',
    'email',
    'sign_in_count'
    // 'director',
    // 'runtime',
    // {name: 'released', type: 'date', dateFormat: 'Y-m-d'},
    // 'genre',
    // 'tagline',
    // {name: 'price', type: 'float'},
    // {name: 'available', type: 'bool'}

    /* name:
       The name by which the field will be referenced.

       type:
       The data type in which the raw data item will be converted to when
       stored in the record. Values may be 'int', 'float', 'string', 'date',
       or 'bool'.

       dateFormat:
       If the type of data to be held in the field is a date type, then
       we need to specify a format string as used by the Date.parseDate function.
    */
]);

// Store

var store = new Ext.data.Store({
    url: '<%= admin_list_path( :need_data => true ) %>',
    reader: new Ext.data.XmlReader({
        record:'row'                  // The repeated element which contains row information
        // idPath:'id',
        // totalProperty: "results",   // The element which contains the total dataset size (optional)
        // idProperty: "id",           // The element within the row that provides an ID for the record (optional)
        // messageProperty: "msg"
    }, Admin),
    autoLoad: true
});

// Grid

var grid = new Ext.grid.GridPanel({
    renderTo: Ext.getBody(),
    frame: true,
    title: 'Admin Database',
    autoHeight: true,
    width: 700,
    store: store,
    colModel: new Ext.grid.ColumnModel({
        defaultSortable: true,
        columns: [
            {header: "ID",            dataIndex: 'id',            width: 50},
            {header: "Email Address", dataIndex: 'email',         width: 500},
            {header: "Sign in count", dataIndex: 'sign_in_count', width: 150}
        ]
    })
});

// Window

var admin_list_window = new Ext.Window({
    autoHeight: true,
    maximizable : false,
    resizable: false,
    modal: true,
    y: 200,
    width: 700,
    layout: 'fit',
    title: 'Rails4me admin database',

    items: [
      grid
    ],

    tbar:[
        {
            xtype : 'button',
            icon: '../images/exticons/worksheet.png',
            text  : ' Information / About administrator',
            listeners : {
                click: function() {
                    var record = grid.selModel.getSelected();
                    if (grid.getSelectionModel().hasSelection()) {
                        Ext.Ajax.request({
                            url: '<%= admin_show_path %>',
                            method: 'POST',
                            params: {
                                id: record.data.id
                            },
                            success: function(response) {
                                var response_text = response.responseText;
                                eval(response_text);
                            },
                            failure: function(resp) {
                                Ext.Msg.show({
                                    title: 'Error!',
                                    msg: 'Bad response from server!',
                                    icon: Ext.MessageBox.ERROR,
                                    buttons: Ext.MessageBox.OK
                                });
                            }
                        });
                    }
                    else {
                        Ext.Msg.show({
                            title: 'Rails4me_app',
                            msg: 'Please, first select a ROW! ',
                            icon: Ext.MessageBox.INFO,
                            buttons: Ext.MessageBox.OK
                        });
                    }
                }
            }
        }
    ]

});
admin_list_window.show();

app/views/admin/show.js.erb
// Record definition

var Admin = Ext.data.Record.create([
    'id',
    'email',
    'sign_in_count',
    'created_at',
    'updated_at',
    'current_sign_in_ip',
    'last_sign_in_ip',
    'current_sign_in_at',
    'last_sign_in_at'
    // 'director',
    // 'runtime',
    // {name: 'released', type: 'date', dateFormat: 'Y-m-d'},
    // 'genre',
    // 'tagline',
    // {name: 'price', type: 'float'},
    // {name: 'available', type: 'bool'}

    /* name:
       The name by which the field will be referenced.

       type:
       The data type in which the raw data item will be converted to when
       stored in the record. Values may be 'int', 'float', 'string', 'date',
       or 'bool'.

       dateFormat:
       If the type of data to be held in the field is a date type, then
       we need to specify a format string as used by the Date.parseDate function.
    */
]);

// Store

var store = new Ext.data.Store({
    url: '<%= admin_show_path( :need_data => true, :id => @admin.id ) %>',
    reader: new Ext.data.XmlReader({
        record:'row'                  // The repeated element which contains row information
        // idPath:'id',
        // totalProperty: "results",   // The element which contains the total dataset size (optional)
        // idProperty: "id",           // The element within the row that provides an ID for the record (optional)
        // messageProperty: "msg"
    }, Admin),
    autoLoad: true
});

// Grid

var grid = new Ext.grid.GridPanel({
    renderTo: Ext.getBody(),
    frame: true,
    title: 'Admin Database',
    autoHeight: true,
    width: 700,
    store: store,
    colModel: new Ext.grid.ColumnModel({
        defaultSortable: true,
        columns: [
            {header: "ID",                 dataIndex: 'id',                 width: 50},
            {header: "Email Address",      dataIndex: 'email',              width: 200},
            {header: "Sign in count",      dataIndex: 'sign_in_count',      width: 100},
            {header: "created_at",         dataIndex: 'created_at',         width: 100},
            {header: "updated_at",         dataIndex: 'updated_at',         width: 100},
            {header: "current_sign_in_ip", dataIndex: 'current_sign_in_ip', width: 100},
            {header: "last_sign_in_ip",    dataIndex: 'last_sign_in_ip',    width: 100},
            {header: "current_sign_in_at", dataIndex: 'current_sign_in_at', width: 100},
            {header: "last_sign_in_at",    dataIndex: 'last_sign_in_at',    width: 100}
        ]
    })
});


// Window

var admin_show_window = new Ext.Window({
    autoHeight: true,
    maximizable : false,
    resizable: false,
    modal: true,
    y: 200,
    width: 950,
    layout: 'fit',
    title: '<%= "#{@admin.email} | Admin datasheet "%>',

    items: [
      grid
    ]

});
admin_show_window.show();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4me</title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
  <!--[if lt IE 8]>
    <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection"/>
  <![endif]-->
</head>
<body>

  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% end %>

  <div id="block_1">
    <div class="container" id="header">
      <div class="span-24">
        <div class="span-18" id="left">
          &nbsp;
        </div>
        <div class="span-6 last" id="right">
        </div>
      </div>
    </div>
  </div>

  <div id="block_2">
    <div class="container">
      <div class="span-24">
        <div class="span-18" id="content">
          <div class="text">
            <%= yield %>
          </div>
        </div>
        <div class="span-6 last" id="list">
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails44me</title>

  <!-- CSS -->

  <%= stylesheet_link_tag "site" %>
  <%= stylesheet_link_tag "../extjs/resources/css/ext-all" %>
  <%= stylesheet_link_tag "../extjs/resources/css/xtheme-gray" %>

  <!-- JS -->

  <%= javascript_include_tag "jquery", "rails" %>
  <%= javascript_include_tag "../extjs/adapter/ext/ext-base" %>
  <%= javascript_include_tag "../extjs/ext-all-debug" %>
  <%= javascript_include_tag "../extjs/src/locale/ext-lang-hu" %>
  <%= javascript_include_tag "../ckeditor/ckeditor" %>
  <%= javascript_include_tag "htmleditor_plugins/ext_ckeditor_plugin" %>

  <script type="text/javascript">
    Ext.BLANK_IMAGE_URL = "<%= Rails.root %>/public/images/ext_default_image/s.gif"
  </script>

  <!-- CSRF -->

  <%= csrf_meta_tag %>

</head>
<body>

  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% end %>

  <div id="block_1">
    <div class="container" id="header">
      <div class="span-24">
        <div class="span-12" id="left">
          &nbsp;
        </div>
        <div class="span-12 last" id="right">
          <div id="login_informaciok">
            <% if admin_signed_in? %>
              Time : <b><%= current_admin.current_sign_in_at %></b>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="tartalom">
  </div>

  <!-- EXTJS TOOLBAR -->

  <div id="main_content">

  <script type="text/javascript">


      // Ext.BLANK_IMAGE_URL = '/extjs/resources/images/default/s.gif';


      // XSRF protection
      Ext.Ajax.on('beforerequest', function(o) {
          var csrf = Ext.select("meta[name='csrf-token']").first();
          if (csrf) {
              o.defaultHeaders = Ext.apply(o.defaultHeaders || {}, {'X-CSRF-Token': csrf.getAttribute('content')});
          }
      });

      // Hide the DOM class
      // Ext.Element.select(".tartalom").hide();

      if (Ext.Element.select(".notice")) {
        var notice = Ext.Element.select(".notice"); // insert element to a variable

          function slideOutNotice() { //function slide out notice
              notice.slideOut('t', {
                  endOpacity: 0, //can be any value between 0 and 1 (e.g. .5)
                  easing: 'easeOut',
                  duration: 3,
                  remove: true
              });
          }

        setTimeout("slideOutNotice()",2000); // wait 2 seconds before run the slideOutNotice
      }

      var myMask = new Ext.LoadMask(Ext.getBody(), {msg:"Kérem várjon..."});
      // myMask.show();

      var tb = new Ext.Toolbar({
          renderTo: Ext.getBody(),
          autoWidth: true,
          items: [
              {
                  xtype: 'button',
                  icon: '../images/exticons/project.png',
                  text: 'Project administration',
                  handler: function() {
                      myMask.show();
                      Ext.Ajax.request({
                          url: '<%= projects_index_path %>',
                          success: function(response){

                             var response_text = response.responseText;
                              eval(response_text);
                              myMask.hide();
                          },
                          failure: function(resp) {
                              Ext.Msg.alert('Hiba!', 'Probléma történt a válaszadáskor!!');
                          }
                      });
                  }

              },
              '-',
              {
                  xtype: 'button',
                  id: "describe_btn",
                  icon: '../images/exticons/describe.png',
                  text: 'Describe administration',
                  handler: function() {
                      myMask.show();
                      Ext.Ajax.request({
                          url: '<%= describes_index_path %>',
                          success: function(response){
                             var response_text = response.responseText;
                              eval(response_text);
                              myMask.hide();
                          },
                          failure: function(resp) {
                              Ext.Msg.alert('Error!', 'Bad response from server!');
                          }
                      });
                  }
              },
              '-',
              {
                  xtype: 'button',
                  icon: '../images/exticons/search.png',
                  text: 'Search',
                  handler: function() {
                      Ext.Ajax.request({
                          url: '<%= search_path %>',
                          success: function(response){
                             var response_text = response.responseText;
                              eval(response_text);
                          },
                          failure: function(resp) {
                              Ext.Msg.alert('Error!', 'Bad response from server!');
                          }
                      });
                  }
              },
              '->',
              {
                  xtype: 'button',
                  id: 'admin',
                  icon: '../images/exticons/admin.png',
                  text: 'Admins!',
                  handler: function() {
                      Ext.Ajax.request({
                          url: '<%= admin_list_path %>',
                          success: function(response){
                             var response_text = response.responseText;
                             eval(response_text);
                          },
                          failure: function(resp) {
                              Ext.Msg.alert('Hiba!', 'Probléma történt a válaszadáskor!!');
                          }
                      });
                  }

              },
              '-',
              'You logged in with this email : <%= current_admin.email %>',
              '-',
              {
                  xtype: 'box',
                  autoEl: {tag: 'a', href: '<%= destroy_admin_session_path %>', html: 'Logout'}
              }
          ]
      });

  </script>

</div>
</body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4me</title>  
  <!-- CKEDITOR -->

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shCore" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushBash" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushCpp" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushCSharp" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushCss" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushDelphi" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushDiff" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushGroovy" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushJava" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushJScript" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushPhp" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushPlain" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushPython" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushRuby" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushScala" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushSql" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushVb" %>
  <%= javascript_include_tag "../ckeditor/plugins/syntaxhighlight/scripts/shBrushXml" %>
  <%= stylesheet_link_tag "syntaxhighlight/shCore" %>
  <%= stylesheet_link_tag "syntaxhighlight/shThemeDefault" %>

  <%= javascript_include_tag :defaults %>
  <!--[if lt IE 8]>
    <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection"/>
  <![endif]-->

  <script type="text/javascript">
    SyntaxHighlighter.config.clipboardSwf = 'public/ckeditor/plugins/syntaxhighlight/scripts/clipboard.swf';
    SyntaxHighlighter.all();
   </script>

</head>
<body>

  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  
  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% end %>

  <div id="block_1">
    <div class="container" id="header">
      <div class="span-24">
        <div class="span-18" id="left">
          &nbsp;
        </div>
        <div class="span-6 last" id="right">                    
        </div>
      </div>
    </div>
  </div>
  
  <div id="block_2">
    <div class="container">
      <div class="span-24">
        <div class="span-18" id="content">
          <div class="text">
            <%= yield %>
          </div>
        </div>
        <div class="span-6 last" id="list">
          <div class="right_container">
            <%= yield :right %>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4me</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <!--[if lt IE 8]>
    <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection"/>
  <![endif]-->
</head>
<body>

  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  
  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% end %>

  <div id="block_1">
    <div class="container" id="header">
      <div class="span-24">
        <div class="span-18" id="left">
          Ra!ls4me          
        </div>
        <div class="span-6 last" id="right">          
          <%= link_to "Kijelentkezés", destroy_admin_session_path %><br/>
        </div>
      </div>
    </div>
  </div>
  
  <div id="block_2">
    <div class="container">
      <div class="span-24">
        <div class="span-18" id="content">
          <div class="text">
            <%= yield %>
          </div>
        </div>
        <div class="span-6 last" id="list">
          <div class="jobb_oldal_project_lista">            
            If you want to create a project please login!
          </div>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/shared/_describe.html.erb
<% content_for :right do %>
  <h1>Describes</h1>
  <% @describes.each do |describe| %>
    <%= link_to "#{describe.title}", describe_path(describe.id) %><br/>
  <% end %>
<% end %>

app/views/shared/_describes_list.html.erb
<% content_for :right do %>
<h1>Describes</h1>
  <% @describes.each do |describe| %>    
    <%= link_to "#{describe.title}", frontend_path(describe.id) %><br/>
  <% end %>
<% end %>

app/views/shared/_frontend_projects.html.erb
<% content_for :right do %>
  <% @projects.each do |project| %>
    <%= project.name %><br/><br/>
  <% end %>
<% end %>

app/views/shared/_list_describes.html.erb
<% content_for :listing_describes do %>
  <% @describes.each do |describe| %>
        <%= describe.title %><br/>
        <%= describe.short_description %><br/>
        <br/><br/>
    <% end %>
<% end %>

app/views/shared/_project.html.erb
<% content_for :listing_projects do %>
  <%= link_to"#{project.name}", show_all_describe_path(project.id) %><br/>
  <%= project.description %><br/><br/>
<% end %>

app/views/shared/_projects_list.html.erb
<% content_for :right do %>
<h1>Projects</h1>
  <% @projects.each do |project| %>
    <%= project.name %><br/><br/>
  <% end %>
<% end %>