config/routes.rb
Rails4me::Application.routes.draw do

  get "search/index"

  get "admin/list"

  # Projects routing

  match '/projects/index' => 'projects#index', :as => 'projects_index'
  match '/projects/new' => 'projects#new', :as => 'new_project'
  match '/projects/show' => 'projects#show', :as => 'show_project'
  match '/projects/create' => 'projects#create', :as => 'create_project'
  match '/projects/edit' => 'projects#edit', :as => 'edit_project'
  match '/projects/update/:id' => 'projects#update', :as => 'update_project'
  match '/projects/destroy' => 'projects#destroy', :as => 'destroy_project'
  # Show project describes
  match '/projects/show_project_describes' => 'projects#show_project_describes', :as => 'show_project_describes'

  # Describes routing

  match '/describes/index' => 'describes#index', :as => 'describes_index'
  match '/describes/new' => 'describes#new', :as => 'new_describe'
  match '/describes/create' => 'describes#create', :as => 'create_describe'
  match '/describes/edit' => 'describes#edit', :as => 'edit_describe'
  match '/describes/update/:id' => 'describes#update', :as => 'update_describe'
  match '/describes/destroy' => 'describes#destroy', :as => 'destroy_describe'
  match '/describes/show_describe_information' => 'describes#show_describe_information', :as => 'show_describe_information'

  # Admin routing

  match '/admin/list' => 'admin#list', :as => 'admin_list'
  match '/admin/show' => 'admin#show', :as => 'admin_show'

  # Search Routing

  match '/search/search' => 'search#search', :as => 'search'
  match '/search/founded_items' => 'search#founded_items', :as => 'founded_items'


  #-------------------------------------------------------------------------------------------------------------------#
  #-------------------------------------------------------------------------------------------------------------------#

  # Others

  root :to => "frontend#index"
  get "backend/index"
  # resources :describes
  # match '/describes/:id' => 'describes#show', :as => 'backend_describe_show', :path => '/backend/describe/:id'
  # match '/backend/search' => 'backend#search', :as => 'search', :path => '/backend/search'

  devise_for :admins do
    get "admin", :to => "devise/sessions#new"
  end

  #scope :path_names => { :show_all => "allprojects" } do
  #  resources :describes do
  #    get 'show_all', :on => :member
  #  end
  # end

  resources :frontend do
    member do
      get 'show'
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :describes
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_admin!
  layout "backend"

  # GET /projects
  # GET /projects.xml
  def index

    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      @projects = Project.all(:include => :describes)
      @project_list = @projects.map do |project|
        {:id => project.id, :name => project.name, :description => project.description, :describes => project.describes.size}
      end

      json = @project_list.to_json

      respond_to do |format|
        format.json { render :json=>json }
      end
    end

  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project_id = params[:id]
    @project = Project.find(@project_id)
    unless params[:need_data]
      respond_to do |format|
        format.js
      end
    else
      @projects = Project.all
      render :json => { :success => true, :projects => @projects}
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new
    respond_to do |format|
      format.js
    end
  end

  # GET /projects/1/edit
  def edit

    # Always know this
    @project_id = params[:id]

    # If don't need data create simple window
    unless params[:need_data]

      # Find the project
      @project = Project.find(@project_id)

      # Find project describes, call show_project_describes
      show_project_describes(@project_id)

      respond_to do |format|
        # Edit JS the simple window
        format.js
      end

    else # If need data for the grid or the form then

      # Find the project
      @project = Project.find(@project_id)

      # Find project describes, call show_project_describes
      show_project_describes(@project_id)

      # Project describes length
      @des = @project.describes.length

      if params[:from] == 'grid'
        # Response in xml to describes grid
        respond_to do |format|
          format.xml
        end
      else
        # Create xml to project form
        render :xml => { :success=> true, :project => @project }
      end

    end
  end

  def show_project_describes(project_id)
    @project_describes = Describe.find(:all, :conditions => ["project_id=?", project_id])
    return @project_describes
  end

  def create
    @project = Project.new(params[:project])
    
      if @project.save
        render :json => { :success => :true }
      else
        render :json => { :failure => :true }
      end

  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project_id = params[:id]
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      render :json => {:success => true}
    else
      render :json => {:failure => true}
     end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    # If project has describe then cannot delete!
    @describe = Describe.find_by_project_id(params[:id])
    if @describe
      render :json => {:failure => true}
    else
      @project.destroy
      render :json => {:success => true}
    end
    
  end
end

app/helpers/models/project.rb
class Project < ActiveRecord::Base
  has_many :describes
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.js.erb
// If we have describes for the project
<% if @project_describes.length > 0 %>
/* GRID */

// Record definition

var describes_data = Ext.data.Record.create([
    'id',
    'title',
    'short_description'

]);

// Store

var describes_store = new Ext.data.Store({
    id: 'project_describes_store',
    url: '<%= edit_project_path(:id => @project_id, :need_data => true, :from => 'grid') %>',
    reader: new Ext.data.XmlReader({
        record:'row'                  // The repeated element which contains row information
        // idPath:'id',
        // totalProperty: "results",   // The element which contains the total dataset size (optional)
        // idProperty: "id",           // The element within the row that provides an ID for the record (optional)
        // messageProperty: "msg"
    }, describes_data),
    autoLoad: true
});

var describes_grid = new Ext.grid.GridPanel({
    id: 'project_describes_list_grid',
    closable: true,
    title : 'Describes list: <%= @project_describes.length %> describe\(s\)!',
    renderTo : Ext.getBody(),
    store: describes_store,
    autoHeight : true,
    loadMask: true,

    // VIEW

    view : new Ext.grid.GridView(),

    // SELMODEL

    selModel : new Ext.grid.RowSelectionModel({
        singleSelect : true
    }),

    // COLMODEL

    colModel: new Ext.grid.ColumnModel([
        {
            hidden: true,
            dataIndex : 'id'
        },
        {
            header : 'Describe name',
            sortable : true,
            width: '200px',
            dataIndex : 'title'
        },
        {
            header : 'Describe short description',
            sortable : true,
            width: '400px',
            dataIndex : 'short_description'
        }
    ]),

    // LISTENER

    listeners : {
        rowdblclick: function(dv, record, item, index, e) {
            var record = describes_grid.selModel.getSelected();
            Ext.Ajax.request({
                url: '<%= edit_describe_path %>',
                params: {
                  id: record.data.id
                },
                success: function(response) {
                    var response_text = response.responseText;
                    eval(response_text);
                },
                failure: function(resp) {
                    Ext.Msg.alert('Error!', 'Bad response from server!');
                }
            });
        }
    }

});

<% end %>



var edit_project_form = new Ext.form.FormPanel({
    id: 'editProjectForm',
    url: '<%= update_project_path(@project_id) %>',
    labelWidth: 130,
    renderTo: Ext.getBody(),
    frame: true,
    autoWidth: true,

    reader: new Ext.data.XmlReader({
        record: 'project',
        success: '@success'
    },
       [
                {name: 'project[id]', mapping: 'id', hidden: true},
                {name: 'project[name]', mapping: 'name'},
                {name: 'project[description]', mapping: 'description'}
            ]
          //  ['id', 'name', 'owner']
    ),

    items:[
        {
            xtype: 'textfield',
            hidden: true,
            name: 'project[id]'
        },
        {
            xtype: 'textfield',
            fieldLabel: 'Project name',
            allowBlank: false,
            width: '98%',
            name: 'project[name]'
        },
        {
            xtype: 'textarea',
            fieldLabel: 'Project description',
            allowBlank: false,
            width: '98%',
            name: 'project[description]'
        }

    ],

    buttons:[
        {

            text: 'Save',
            icon: '../images/exticons/save.png',
            handler: function() {
                edit_project_form.getForm().submit({
                    success: function(form, action) {
                        Ext.Msg.alert('Success!', 'You saved the new project to database successfully!');
                        Ext.getCmp('edit_project_window').close();
                        Ext.getCmp('project_list_grid').getStore().reload();
                    },
                    failure: function(form, action) {
                        Ext.Msg.show({
                            title: 'Rails4me_app',
                            msg: 'Cannot saved into the database,<br/> please check your fields!',
                            icon: Ext.MessageBox.INFO,
                            buttons: Ext.MessageBox.OK
                        });
                    }
                });

            }

        },

        {

            text: 'Cancel',
            icon: '../images/exticons/cancel.png',
            handler: function() {
                Ext.getCmp('edit_project_window').close();
                // Index grid refresh
                Ext.getCmp('project_list_grid').store.reload();
            }

        }

    ]

});

var edit_project_window = new Ext.Window({
    id: 'edit_project_window',
    autoHeight: true,
    width: 600,
    modal: true,
    layout: 'form',
    title: 'Updating \"<%= @project.name %>\" project',
    contentEL: "Describes to this project : <%= @project_describes %> ",

    items: [
      // Load form and grid into window
      edit_project_form
      <% if @project_describes.length > 0 %>
      ,describes_grid
      <% end %>
    ]
});

edit_project_window.show();

edit_project_form.getForm().load({
    method:'get',
    url: '<%= edit_project_path(:id => @project_id, :need_data => 'true')%>',
    waitMsg: 'Loading...'
});

app/views/projects/index.js.erb
// Basic mask object:
// var myMask = new Ext.LoadMask(Ext.getBody(), {msg:"Please wait..."});

var grid = new Ext.grid.GridPanel({
    id: 'project_list_grid',
    closable: true,
    title : 'Project list',
    autoHeight : true,
    loadMask: true, // or the object => myMask

    // VIEW

    view : new Ext.grid.GridView(),

    // STORE

    store: new Ext.data.Store({
        id: 'project_store',
        autoLoad: true,
        url: '<%= projects_index_path(:need_data => 'true') %>',

        reader: new Ext.data.JsonReader({
            idProperty:'id'
        },
                [
                    {name: 'id', mapping: 'id'},
                    {name: 'name', mapping: 'name'},
                    {name: 'description', mapping: 'description'},
                    {name: 'describes', mapping: 'describes'}
                ]

                )
    }),

    // SELMODEL

    selModel : new Ext.grid.RowSelectionModel({
        singleSelect : true
    }),

    // COLMODEL

    colModel: new Ext.grid.ColumnModel([
        {
            header : 'Project name',
            sortable : true,
            width: '200px',
            dataIndex : 'name'
        },
        {
            header : 'Project description',
            sortable : true,
            width: '400px',
            dataIndex : 'description'
        },
        {
            header : 'Describes',
            sortable : true,
            width: '200px',
            dataIndex : 'describes'
        }
    ]),

    // LISTENER

    listeners : {
        rowdblclick: function(dv, record, item, index, e) {
           var record = grid.selModel.getSelected();
           Ext.Ajax.request({
                    url: '<%= edit_project_path %>',
                    method: 'POST',
                    params: {
                      id: record.data.id
                    },
                    success: function(response) {
                        var response_text = response.responseText;
                        eval(response_text);
                    },
                    failure: function(resp) {
                        Ext.Msg.alert('Hiba', 'Probléma történt a válaszadáskor!');
                    }
           });
        }
    }

});

var project_index_window = new Ext.Window({
    id: 'window',
    autoHeight: true,
    maximizable : true,
    modal: true,
    y: 200,
    width: 800,
    layout: 'fit',
    title: 'Rails4me projects',

    items: [
      grid
    ],

    tbar: [
        {
           xtype : 'button',
           icon: '../images/exticons/add_project.png',
           text  : 'Create a new project',
            handler: function() {
                Ext.Ajax.request({
                    url: '<%= new_project_path %>',
                    success: function(response) {
                        var response_text = response.responseText;
                        eval(response_text);
                    },
                    failure: function(resp) {
                        Ext.Msg.alert('Error!', 'Bad response from server!');
                    }
                });
            }
        },
        '-',
        {
           xtype : 'button',
           icon: '../images/exticons/edit_project.png',
           text  : 'Edit selected project',
           listeners : {
                click: function() {
                    var selected_row = grid.selModel.getSelected();
                    if (grid.getSelectionModel().hasSelection()) {
                        Ext.Ajax.request({
                            url: '<%= edit_project_path %>',
                            method: 'POST',
                            params: {
                                id: selected_row.data.id
                            },
                            success: function(response) {
                                var response_text = response.responseText;
                                eval(response_text);
                            },
                            failure: function(resp) {
                                Ext.Msg.alert('ERROR!', 'Bad response from server!');
                            }
                        });
                    }
                    else {
                        Ext.Msg.alert('ERROR!', 'Please first select a row!');
                    }
                }
           }

        },
        '-',
        {
            xtype : 'button',
            icon: '../images/exticons/delete_project.png',
            text  : 'Remove selected project',
            handler: function() {
                var selected_row = grid.getSelectionModel().getSelected();
                if (grid.getSelectionModel().hasSelection()) {

                    Ext.Msg.show({
                        title:'Save Changes?',
                        msg: 'Would you like to delete selected project?',
                        buttons: Ext.Msg.YESNOCANCEL,
                        icon: Ext.MessageBox.QUESTION,
                        fn: function(btn){
                          if (btn == 'yes') {

                              Ext.Ajax.request({
                                  waitMsg: "Please wait",
                                  url: '<%= destroy_project_path %>',
                                  method: 'POST',
                                  params: {
                                      id: selected_row.data.id
                                  },
                                  success: function() {
                                      Ext.Msg.alert('Success!', 'Sucessfully destroyed the project!');
                                      Ext.getCmp('project_list_grid').getStore().reload();
                                      // var response_text = response.responseText;
                                      // eval(response_text);
                                  },
                                  failure: function() {
                                      Ext.Msg.alert('Hiba!', 'Probléma történt a válaszadáskor');
                                  }
                              });

                          }
                        }
                    });
                }
                else {
                    Ext.Msg.alert('ERROR!', 'Please first select a row!');
                }
            }
        }
    ],

    bbar: [
        {
            xtype : 'button',
            icon: '../images/exticons/worksheet.png',
            text  : ' Information / Worksheet selected project',
            listeners : {
                click: function() {
                    var record = grid.selModel.getSelected();
                    if (grid.getSelectionModel().hasSelection()) {
                        Ext.Ajax.request({
                            url: '<%= show_project_path %>',
                            method: 'POST',
                            params: {
                                id: record.data.id
                            },
                            success: function(response) {
                                var response_text = response.responseText;
                                eval(response_text);
                            },
                            failure: function(resp) {
                                Ext.Msg.alert('ERROR!', 'Bad response from server!');
                            }
                        });
                    }
                    else {
                        Ext.Msg.alert('ERROR!', 'Please first select a row!');
                    }
                }
            }
        }
    ]

});
project_index_window.show();

app/views/projects/new.js.erb
Ext.QuickTips.init();

var project_form = new Ext.form.FormPanel({
    url: '<%= create_project_path %>',
    labelWidth: 130,
    renderTo: Ext.getBody(),
    frame: true,
    autoWidth: true,
    items:[
        {
            xtype: 'textfield',
            allowBlank: false,
            fieldLabel: 'Project name',
            width: '98%',
            name: 'project[name]'
        },
        {
            xtype: 'textarea',
            allowBlank: false,
            fieldLabel: 'Project description',
            width: '98%',
            name: 'project[description]'
        }

    ],

    buttons:[
        {

            text: 'Save',
            icon: '../images/exticons/save.png',
            handler: function() {
                project_form.getForm().submit({
                    success: function(form, action) {
                        Ext.getCmp('project_list_grid').getStore().reload();
                        Ext.Msg.alert('Success!', 'You saved the new project to database successfully!');
                        Ext.getCmp('new_project_form_window').close();
                    },
                    failure: function(form, action) {
                        Ext.Msg.show({
                            title: 'Rails4me_app',
                            msg: 'Cannot saved into the database,<br/> please check your fields!',
                            icon: Ext.MessageBox.INFO,
                            buttons: Ext.MessageBox.OK
                        });
                    }
                });

            }

        },

        {

            text: 'Cancel',
            icon: '../images/exticons/cancel.png',
            handler: function() {
                Ext.getCmp('new_project_form_window').close();
            }

        }

    ]

});

var new_project_window = new Ext.Window({
    id: 'new_project_form_window',
    autoHeight: true,
    width: 600,
    modal: true,
    layout: 'form',
    title: 'Create a new project',

    items: [
      // Load form into window
      project_form
    ]
});

new_project_window.show();

app/views/projects/show.js.erb
var project_worksheet_window = new Ext.Window({
    autoHeight: true,
    maximizable : true,
    y: 200,
    width: 800,
    layout: 'fit',
    title: 'Show project worksheet',
    padding: 20,
    html: '<b>Project Datasheet | <%= @project.name %></b><br/><br/><%= @project.description %><br/><br/><%= "Created : #{@project.created_at}" %><b> | </b> <%= "Updated : #{@project.updated_at}"%>'
});
project_worksheet_window.show();